version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql-swift
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: swift_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db-init.sql:/docker-entrypoint-initdb.d/db-init.sql

volumes:
  mysql_data:
